name: Python tests, build, and deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate coverage report
        run: |
          pytest --cov=seleniumprint --cov-report=html --cov-branch
        env:
          CI: true
      - name: Display coverage report
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: coverage-report
          path: htmlcov
      - name: Upload PDF artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-pdf
          path: tests/test.pdf
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install wheel
          pip install twine
      - name: Build wheel
        run: python setup.py bdist_wheel
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/*.whl
        if: startsWith(github.ref, 'refs/tags/')
      - name: Upload package to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*.whl
