name: Python tests and build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  tags:
    # Match any tag starting with "v"
    - 'v*'

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest
        env:
          SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      - name: Upload PDF artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-pdf
          path: tests/test.pdf
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install wheel
      - name: Build wheel
        run: python setup.py bdist_wheel
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheel
          path: dist/*.whl
        if: startsWith(github.ref, 'refs/tags/')
